name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username michabirklbauer --password-stdin
        docker build . --file Dockerfile --tag michabirklbauer/piaweb:latest
        docker push michabirklbauer/piaweb:latest
        GIT_SHA="$(git rev-parse --short HEAD)"
        docker tag michabirklbauer/piaweb:latest michabirklbauer/piaweb:$GIT_SHA
        docker push michabirklbauer/piaweb:$GIT_SHA
